version: "3.8"

services:
  datalakes-be:
    image: datalakes-be
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=docker
      - DB_PASSWORD=docker
      - DB_NAME=datalakes

  db:
    image: postgres:11.12
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - ./db/datalakes_schema.sql:/docker-entrypoint-initdb.d/datalakes_schema.sql
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker"]
      interval: 30s
      timeout: 30s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com  # Set your desired email
      - PGADMIN_DEFAULT_PASSWORD=supersecret   # Set your desired password
    ports:
      - 5050:80
    depends_on:
      - db